// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/coordinator.proto

package grpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyUsage int32

const (
	KeyUsage_KEY_USAGE_UNSPECIFIED KeyUsage = 0
	KeyUsage_KEY_USAGE_OPERATIONAL KeyUsage = 1 // 运营用途
	KeyUsage_KEY_USAGE_USER        KeyUsage = 2 // 用户用途
)

// Enum value maps for KeyUsage.
var (
	KeyUsage_name = map[int32]string{
		0: "KEY_USAGE_UNSPECIFIED",
		1: "KEY_USAGE_OPERATIONAL",
		2: "KEY_USAGE_USER",
	}
	KeyUsage_value = map[string]int32{
		"KEY_USAGE_UNSPECIFIED": 0,
		"KEY_USAGE_OPERATIONAL": 1,
		"KEY_USAGE_USER":        2,
	}
)

func (x KeyUsage) Enum() *KeyUsage {
	p := new(KeyUsage)
	*p = x
	return p
}

func (x KeyUsage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyUsage) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_coordinator_proto_enumTypes[0].Descriptor()
}

func (KeyUsage) Type() protoreflect.EnumType {
	return &file_proto_coordinator_proto_enumTypes[0]
}

func (x KeyUsage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyUsage.Descriptor instead.
func (KeyUsage) EnumDescriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateMasterKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 链路跟踪 ID
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`                    // 区块链网络名称（如 ethereum）
	KeyType       string                 `protobuf:"bytes,3,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"` // 密钥类型（如 ecdsa-secp256k1）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMasterKeyRequest) Reset() {
	*x = CreateMasterKeyRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterKeyRequest) ProtoMessage() {}

func (x *CreateMasterKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateMasterKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMasterKeyRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateMasterKeyRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *CreateMasterKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type CreateMasterKeyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TraceId        string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	KeyName        string                 `protobuf:"bytes,2,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`                      // 主密钥名称，格式：{chain}-master-key
	SeedCiphertext string                 `protobuf:"bytes,3,opt,name=seed_ciphertext,json=seedCiphertext,proto3" json:"seed_ciphertext,omitempty"` // Vault 加密的种子密文
	PublicKey      string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                // 公钥
	Bip44Path      string                 `protobuf:"bytes,5,opt,name=bip44_path,json=bip44Path,proto3" json:"bip44_path,omitempty"`                // BIP-44 路径
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMasterKeyResponse) Reset() {
	*x = CreateMasterKeyResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterKeyResponse) ProtoMessage() {}

func (x *CreateMasterKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateMasterKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMasterKeyResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateMasterKeyResponse) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *CreateMasterKeyResponse) GetSeedCiphertext() string {
	if x != nil {
		return x.SeedCiphertext
	}
	return ""
}

func (x *CreateMasterKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateMasterKeyResponse) GetBip44Path() string {
	if x != nil {
		return x.Bip44Path
	}
	return ""
}

type CreateDerivedKeyRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TraceId                string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Chain                  string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`                                                                      // 区块链网络名称
	MasterKeyName          string                 `protobuf:"bytes,3,opt,name=master_key_name,json=masterKeyName,proto3" json:"master_key_name,omitempty"`                               // 主密钥名称
	MasterKeyPemCiphertext string                 `protobuf:"bytes,10,opt,name=master_key_pem_ciphertext,json=masterKeyPemCiphertext,proto3" json:"master_key_pem_ciphertext,omitempty"` // 主密钥PEM密文（来自CreateMasterKey返回值）
	KeyUsage               KeyUsage               `protobuf:"varint,4,opt,name=key_usage,json=keyUsage,proto3,enum=coordinator.KeyUsage" json:"key_usage,omitempty"`                     // 密钥用途
	KeyType                string                 `protobuf:"bytes,5,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`                                                   // 密钥类型
	AddressIndex           uint32                 `protobuf:"varint,6,opt,name=address_index,json=addressIndex,proto3" json:"address_index,omitempty"`                                   // 地址索引
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateDerivedKeyRequest) Reset() {
	*x = CreateDerivedKeyRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDerivedKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDerivedKeyRequest) ProtoMessage() {}

func (x *CreateDerivedKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDerivedKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateDerivedKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDerivedKeyRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateDerivedKeyRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *CreateDerivedKeyRequest) GetMasterKeyName() string {
	if x != nil {
		return x.MasterKeyName
	}
	return ""
}

func (x *CreateDerivedKeyRequest) GetMasterKeyPemCiphertext() string {
	if x != nil {
		return x.MasterKeyPemCiphertext
	}
	return ""
}

func (x *CreateDerivedKeyRequest) GetKeyUsage() KeyUsage {
	if x != nil {
		return x.KeyUsage
	}
	return KeyUsage_KEY_USAGE_UNSPECIFIED
}

func (x *CreateDerivedKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *CreateDerivedKeyRequest) GetAddressIndex() uint32 {
	if x != nil {
		return x.AddressIndex
	}
	return 0
}

type CreateDerivedKeyResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TraceId           string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	KeyName           string                 `protobuf:"bytes,2,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`                                 // 派生密钥名称，格式：{chain}-child-{op|user}-{index}
	PrivKeyCiphertext string                 `protobuf:"bytes,3,opt,name=priv_key_ciphertext,json=privKeyCiphertext,proto3" json:"priv_key_ciphertext,omitempty"` // Vault 加密的私钥密文
	PublicKey         string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                           // 公钥
	Bip44Path         string                 `protobuf:"bytes,5,opt,name=bip44_path,json=bip44Path,proto3" json:"bip44_path,omitempty"`                           // BIP-44 路径
	KeyContext        string                 `protobuf:"bytes,6,opt,name=key_context,json=keyContext,proto3" json:"key_context,omitempty"`                        // Vault context
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateDerivedKeyResponse) Reset() {
	*x = CreateDerivedKeyResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDerivedKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDerivedKeyResponse) ProtoMessage() {}

func (x *CreateDerivedKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDerivedKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateDerivedKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDerivedKeyResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateDerivedKeyResponse) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *CreateDerivedKeyResponse) GetPrivKeyCiphertext() string {
	if x != nil {
		return x.PrivKeyCiphertext
	}
	return ""
}

func (x *CreateDerivedKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateDerivedKeyResponse) GetBip44Path() string {
	if x != nil {
		return x.Bip44Path
	}
	return ""
}

func (x *CreateDerivedKeyResponse) GetKeyContext() string {
	if x != nil {
		return x.KeyContext
	}
	return ""
}

type SignRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TraceId           string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Chain             string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`                                                    // 区块链网络名称
	KeyName           string                 `protobuf:"bytes,3,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`                                 // 派生密钥名称
	KeyUsage          KeyUsage               `protobuf:"varint,4,opt,name=key_usage,json=keyUsage,proto3,enum=coordinator.KeyUsage" json:"key_usage,omitempty"`   // 密钥用途
	KeyType           string                 `protobuf:"bytes,5,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`                                 // 密钥类型
	KeyContext        string                 `protobuf:"bytes,6,opt,name=key_context,json=keyContext,proto3" json:"key_context,omitempty"`                        // Vault context
	Message           string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`                                                // 待签名数据
	PrivKeyCiphertext string                 `protobuf:"bytes,8,opt,name=priv_key_ciphertext,json=privKeyCiphertext,proto3" json:"priv_key_ciphertext,omitempty"` // 私钥密文
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *SignRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SignRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *SignRequest) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *SignRequest) GetKeyUsage() KeyUsage {
	if x != nil {
		return x.KeyUsage
	}
	return KeyUsage_KEY_USAGE_UNSPECIFIED
}

func (x *SignRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *SignRequest) GetKeyContext() string {
	if x != nil {
		return x.KeyContext
	}
	return ""
}

func (x *SignRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignRequest) GetPrivKeyCiphertext() string {
	if x != nil {
		return x.PrivKeyCiphertext
	}
	return ""
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // 签名结果（hex 格式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *SignResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SignResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_proto_coordinator_proto protoreflect.FileDescriptor

const file_proto_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x17proto/coordinator.proto\x12\vcoordinator\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"d\n" +
	"\x16CreateMasterKeyRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x19\n" +
	"\bkey_type\x18\x03 \x01(\tR\akeyType\"\xb6\x01\n" +
	"\x17CreateMasterKeyResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\bkey_name\x18\x02 \x01(\tR\akeyName\x12'\n" +
	"\x0fseed_ciphertext\x18\x03 \x01(\tR\x0eseedCiphertext\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1d\n" +
	"\n" +
	"bip44_path\x18\x05 \x01(\tR\tbip44Path\"\xe6\x01\n" +
	"\x17CreateDerivedKeyRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12&\n" +
	"\x0fmaster_key_name\x18\x03 \x01(\tR\rmasterKeyName\x122\n" +
	"\tkey_usage\x18\x04 \x01(\x0e2\x15.coordinator.KeyUsageR\bkeyUsage\x12\x19\n" +
	"\bkey_type\x18\x05 \x01(\tR\akeyType\x12#\n" +
	"\raddress_index\x18\x06 \x01(\rR\faddressIndex\"\xdf\x01\n" +
	"\x18CreateDerivedKeyResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\bkey_name\x18\x02 \x01(\tR\akeyName\x12.\n" +
	"\x13priv_key_ciphertext\x18\x03 \x01(\tR\x11privKeyCiphertext\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1d\n" +
	"\n" +
	"bip44_path\x18\x05 \x01(\tR\tbip44Path\x12\x1f\n" +
	"\vkey_context\x18\x06 \x01(\tR\n" +
	"keyContext\"\x93\x02\n" +
	"\vSignRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x19\n" +
	"\bkey_name\x18\x03 \x01(\tR\akeyName\x122\n" +
	"\tkey_usage\x18\x04 \x01(\x0e2\x15.coordinator.KeyUsageR\bkeyUsage\x12\x19\n" +
	"\bkey_type\x18\x05 \x01(\tR\akeyType\x12\x1f\n" +
	"\vkey_context\x18\x06 \x01(\tR\n" +
	"keyContext\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12.\n" +
	"\x13priv_key_ciphertext\x18\b \x01(\tR\x11privKeyCiphertext\"G\n" +
	"\fSignResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature*T\n" +
	"\bKeyUsage\x12\x19\n" +
	"\x15KEY_USAGE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15KEY_USAGE_OPERATIONAL\x10\x01\x12\x12\n" +
	"\x0eKEY_USAGE_USER\x10\x022\xdc\x02\n" +
	"\fChainService\x12P\n" +
	"\vHealthCheck\x12\x1f.coordinator.HealthCheckRequest\x1a .coordinator.HealthCheckResponse\x12\\\n" +
	"\x0fCreateMasterKey\x12#.coordinator.CreateMasterKeyRequest\x1a$.coordinator.CreateMasterKeyResponse\x12_\n" +
	"\x10CreateDerivedKey\x12$.coordinator.CreateDerivedKeyRequest\x1a%.coordinator.CreateDerivedKeyResponse\x12;\n" +
	"\x04Sign\x12\x18.coordinator.SignRequest\x1a\x19.coordinator.SignResponseB=Z;github.com/koku-web3/go-koku/internal/coordinator/grpc;grpcb\x06proto3"

var (
	file_proto_coordinator_proto_rawDescOnce sync.Once
	file_proto_coordinator_proto_rawDescData []byte
)

func file_proto_coordinator_proto_rawDescGZIP() []byte {
	file_proto_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)))
	})
	return file_proto_coordinator_proto_rawDescData
}

var file_proto_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_coordinator_proto_goTypes = []any{
	(KeyUsage)(0),                    // 0: coordinator.KeyUsage
	(*HealthCheckRequest)(nil),       // 1: coordinator.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 2: coordinator.HealthCheckResponse
	(*CreateMasterKeyRequest)(nil),   // 3: coordinator.CreateMasterKeyRequest
	(*CreateMasterKeyResponse)(nil),  // 4: coordinator.CreateMasterKeyResponse
	(*CreateDerivedKeyRequest)(nil),  // 5: coordinator.CreateDerivedKeyRequest
	(*CreateDerivedKeyResponse)(nil), // 6: coordinator.CreateDerivedKeyResponse
	(*SignRequest)(nil),              // 7: coordinator.SignRequest
	(*SignResponse)(nil),             // 8: coordinator.SignResponse
}
var file_proto_coordinator_proto_depIdxs = []int32{
	0, // 0: coordinator.CreateDerivedKeyRequest.key_usage:type_name -> coordinator.KeyUsage
	0, // 1: coordinator.SignRequest.key_usage:type_name -> coordinator.KeyUsage
	1, // 2: coordinator.ChainService.HealthCheck:input_type -> coordinator.HealthCheckRequest
	3, // 3: coordinator.ChainService.CreateMasterKey:input_type -> coordinator.CreateMasterKeyRequest
	5, // 4: coordinator.ChainService.CreateDerivedKey:input_type -> coordinator.CreateDerivedKeyRequest
	7, // 5: coordinator.ChainService.Sign:input_type -> coordinator.SignRequest
	2, // 6: coordinator.ChainService.HealthCheck:output_type -> coordinator.HealthCheckResponse
	4, // 7: coordinator.ChainService.CreateMasterKey:output_type -> coordinator.CreateMasterKeyResponse
	6, // 8: coordinator.ChainService.CreateDerivedKey:output_type -> coordinator.CreateDerivedKeyResponse
	8, // 9: coordinator.ChainService.Sign:output_type -> coordinator.SignResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_coordinator_proto_init() }
func file_proto_coordinator_proto_init() {
	if File_proto_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_proto_depIdxs,
		EnumInfos:         file_proto_coordinator_proto_enumTypes,
		MessageInfos:      file_proto_coordinator_proto_msgTypes,
	}.Build()
	File_proto_coordinator_proto = out.File
	file_proto_coordinator_proto_goTypes = nil
	file_proto_coordinator_proto_depIdxs = nil
}
