// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: proto/keycreator.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyCreator_HealthCheck_FullMethodName          = "/keycreator.KeyCreator/HealthCheck"
	KeyCreator_Genesis_FullMethodName              = "/keycreator.KeyCreator/Genesis"
	KeyCreator_CreateOperationalKey_FullMethodName = "/keycreator.KeyCreator/CreateOperationalKey"
	KeyCreator_CreateUserKey_FullMethodName        = "/keycreator.KeyCreator/CreateUserKey"
)

// KeyCreatorClient is the client API for KeyCreator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyCreatorClient interface {
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 生成核心主密钥
	Genesis(ctx context.Context, in *GenesisRequest, opts ...grpc.CallOption) (*GenesisResponse, error)
	// 创建运营密钥
	CreateOperationalKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error)
	// 创建用户密钥
	CreateUserKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error)
}

type keyCreatorClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyCreatorClient(cc grpc.ClientConnInterface) KeyCreatorClient {
	return &keyCreatorClient{cc}
}

func (c *keyCreatorClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, KeyCreator_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyCreatorClient) Genesis(ctx context.Context, in *GenesisRequest, opts ...grpc.CallOption) (*GenesisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenesisResponse)
	err := c.cc.Invoke(ctx, KeyCreator_Genesis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyCreatorClient) CreateOperationalKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyResponse)
	err := c.cc.Invoke(ctx, KeyCreator_CreateOperationalKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyCreatorClient) CreateUserKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyResponse)
	err := c.cc.Invoke(ctx, KeyCreator_CreateUserKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyCreatorServer is the server API for KeyCreator service.
// All implementations must embed UnimplementedKeyCreatorServer
// for forward compatibility.
type KeyCreatorServer interface {
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 生成核心主密钥
	Genesis(context.Context, *GenesisRequest) (*GenesisResponse, error)
	// 创建运营密钥
	CreateOperationalKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error)
	// 创建用户密钥
	CreateUserKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error)
	mustEmbedUnimplementedKeyCreatorServer()
}

// UnimplementedKeyCreatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyCreatorServer struct{}

func (UnimplementedKeyCreatorServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedKeyCreatorServer) Genesis(context.Context, *GenesisRequest) (*GenesisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Genesis not implemented")
}
func (UnimplementedKeyCreatorServer) CreateOperationalKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOperationalKey not implemented")
}
func (UnimplementedKeyCreatorServer) CreateUserKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserKey not implemented")
}
func (UnimplementedKeyCreatorServer) mustEmbedUnimplementedKeyCreatorServer() {}
func (UnimplementedKeyCreatorServer) testEmbeddedByValue()                    {}

// UnsafeKeyCreatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyCreatorServer will
// result in compilation errors.
type UnsafeKeyCreatorServer interface {
	mustEmbedUnimplementedKeyCreatorServer()
}

func RegisterKeyCreatorServer(s grpc.ServiceRegistrar, srv KeyCreatorServer) {
	// If the following call panics, it indicates UnimplementedKeyCreatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyCreator_ServiceDesc, srv)
}

func _KeyCreator_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyCreatorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyCreator_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyCreatorServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyCreator_Genesis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenesisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyCreatorServer).Genesis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyCreator_Genesis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyCreatorServer).Genesis(ctx, req.(*GenesisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyCreator_CreateOperationalKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyCreatorServer).CreateOperationalKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyCreator_CreateOperationalKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyCreatorServer).CreateOperationalKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyCreator_CreateUserKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyCreatorServer).CreateUserKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyCreator_CreateUserKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyCreatorServer).CreateUserKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyCreator_ServiceDesc is the grpc.ServiceDesc for KeyCreator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyCreator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keycreator.KeyCreator",
	HandlerType: (*KeyCreatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _KeyCreator_HealthCheck_Handler,
		},
		{
			MethodName: "Genesis",
			Handler:    _KeyCreator_Genesis_Handler,
		},
		{
			MethodName: "CreateOperationalKey",
			Handler:    _KeyCreator_CreateOperationalKey_Handler,
		},
		{
			MethodName: "CreateUserKey",
			Handler:    _KeyCreator_CreateUserKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/keycreator.proto",
}
