// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/keycreator.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_keycreator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keycreator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_keycreator_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_keycreator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keycreator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_keycreator_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 派生的密钥数据
type DerivedCoreKey struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	KeyUsage           uint32                 `protobuf:"varint,1,opt,name=key_usage,json=keyUsage,proto3" json:"key_usage,omitempty"`                              //0：运营密钥进行签名；场景：归集、出账；1：用户密钥进行签名出账；场景：归集
	Bip32KeyCiphertext string                 `protobuf:"bytes,2,opt,name=bip32key_ciphertext,json=bip32keyCiphertext,proto3" json:"bip32key_ciphertext,omitempty"` // 加密后的bip32主密钥 hex 格式
	Context            string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                                                 // 密钥派生上下文标识符，1-36必填，唯一；在 vault 系统加解密时使用；格式类似：m-44-60-0-0-0
	Bip44Path          string                 `protobuf:"bytes,4,opt,name=bip44_path,json=bip44Path,proto3" json:"bip44_path,omitempty"`                            // BIP-44 路径字符串
	DekCiphertext      string                 `protobuf:"bytes,5,opt,name=dek_ciphertext,json=dekCiphertext,proto3" json:"dek_ciphertext,omitempty"`                // DEK 数据加密密钥，用于信封加密
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DerivedCoreKey) Reset() {
	*x = DerivedCoreKey{}
	mi := &file_proto_keycreator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DerivedCoreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DerivedCoreKey) ProtoMessage() {}

func (x *DerivedCoreKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keycreator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DerivedCoreKey.ProtoReflect.Descriptor instead.
func (*DerivedCoreKey) Descriptor() ([]byte, []int) {
	return file_proto_keycreator_proto_rawDescGZIP(), []int{2}
}

func (x *DerivedCoreKey) GetKeyUsage() uint32 {
	if x != nil {
		return x.KeyUsage
	}
	return 0
}

func (x *DerivedCoreKey) GetBip32KeyCiphertext() string {
	if x != nil {
		return x.Bip32KeyCiphertext
	}
	return ""
}

func (x *DerivedCoreKey) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *DerivedCoreKey) GetBip44Path() string {
	if x != nil {
		return x.Bip44Path
	}
	return ""
}

func (x *DerivedCoreKey) GetDekCiphertext() string {
	if x != nil {
		return x.DekCiphertext
	}
	return ""
}

type DerivedChildKey struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PrivKeyCiphertext string                 `protobuf:"bytes,1,opt,name=priv_key_ciphertext,json=privKeyCiphertext,proto3" json:"priv_key_ciphertext,omitempty"` // 加密后的 DER 格式密钥，返回base64编码格式
	PublicKey         string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                           // PKIX格式公钥（使用 ASN.1 数据结构，DER 编码）；返回 PEM 文本格式
	AddressIndex      uint32                 `protobuf:"varint,3,opt,name=address_index,json=addressIndex,proto3" json:"address_index,omitempty"`                 // 地址索引
	Context           string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`                                                // 密钥派生上下文标识符，1-36必填，唯一；在 vault 系统加解密时使用；格式类似：m-44-60-0-0-0
	Bip44Path         string                 `protobuf:"bytes,5,opt,name=bip44_path,json=bip44Path,proto3" json:"bip44_path,omitempty"`                           // BIP-44 路径字符串
	DekCiphertext     string                 `protobuf:"bytes,6,opt,name=dek_ciphertext,json=dekCiphertext,proto3" json:"dek_ciphertext,omitempty"`               // DEK 数据加密密钥，用于信封加密
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DerivedChildKey) Reset() {
	*x = DerivedChildKey{}
	mi := &file_proto_keycreator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DerivedChildKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DerivedChildKey) ProtoMessage() {}

func (x *DerivedChildKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keycreator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DerivedChildKey.ProtoReflect.Descriptor instead.
func (*DerivedChildKey) Descriptor() ([]byte, []int) {
	return file_proto_keycreator_proto_rawDescGZIP(), []int{3}
}

func (x *DerivedChildKey) GetPrivKeyCiphertext() string {
	if x != nil {
		return x.PrivKeyCiphertext
	}
	return ""
}

func (x *DerivedChildKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DerivedChildKey) GetAddressIndex() uint32 {
	if x != nil {
		return x.AddressIndex
	}
	return 0
}

func (x *DerivedChildKey) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *DerivedChildKey) GetBip44Path() string {
	if x != nil {
		return x.Bip44Path
	}
	return ""
}

func (x *DerivedChildKey) GetDekCiphertext() string {
	if x != nil {
		return x.DekCiphertext
	}
	return ""
}

type GenesisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`       // 链路跟踪ID，必填
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"` // 区块链名称，如：bitcoin、ethereum、tron，1-36必填
	KeyType       string                 `protobuf:"bytes,3,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`       // 密钥类型，如ecdsa-secp256k1、ecdsa-secp256r1、eddsa-ed25519，1-36必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisRequest) Reset() {
	*x = GenesisRequest{}
	mi := &file_proto_keycreator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisRequest) ProtoMessage() {}

func (x *GenesisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keycreator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisRequest.ProtoReflect.Descriptor instead.
func (*GenesisRequest) Descriptor() ([]byte, []int) {
	return file_proto_keycreator_proto_rawDescGZIP(), []int{4}
}

func (x *GenesisRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GenesisRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *GenesisRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type GenesisResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Bip32KeyCiphertext string                 `protobuf:"bytes,1,opt,name=bip32key_ciphertext,json=bip32keyCiphertext,proto3" json:"bip32key_ciphertext,omitempty"` // 加密后的bip32主密钥 hex 格式
	Context            string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`                                                 // 密钥派生上下文标识符，1-36必填，唯一；在 vault 系统加解密时使用；格式类似：m-44-60-0-0-0
	Bip44Path          string                 `protobuf:"bytes,3,opt,name=bip44_path,json=bip44Path,proto3" json:"bip44_path,omitempty"`                            // BIP-44 路径字符串
	DekCiphertext      string                 `protobuf:"bytes,4,opt,name=dek_ciphertext,json=dekCiphertext,proto3" json:"dek_ciphertext,omitempty"`                // DEK 数据加密密钥，用于信封加密
	DerivedKeys        []*DerivedCoreKey      `protobuf:"bytes,5,rep,name=derived_keys,json=derivedKeys,proto3" json:"derived_keys,omitempty"`                      // 派生的密钥列表 (运营账户和用户账户)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenesisResponse) Reset() {
	*x = GenesisResponse{}
	mi := &file_proto_keycreator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisResponse) ProtoMessage() {}

func (x *GenesisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keycreator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisResponse.ProtoReflect.Descriptor instead.
func (*GenesisResponse) Descriptor() ([]byte, []int) {
	return file_proto_keycreator_proto_rawDescGZIP(), []int{5}
}

func (x *GenesisResponse) GetBip32KeyCiphertext() string {
	if x != nil {
		return x.Bip32KeyCiphertext
	}
	return ""
}

func (x *GenesisResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *GenesisResponse) GetBip44Path() string {
	if x != nil {
		return x.Bip44Path
	}
	return ""
}

func (x *GenesisResponse) GetDekCiphertext() string {
	if x != nil {
		return x.DekCiphertext
	}
	return ""
}

func (x *GenesisResponse) GetDerivedKeys() []*DerivedCoreKey {
	if x != nil {
		return x.DerivedKeys
	}
	return nil
}

type CreateKeyRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TraceId            string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                  // 链路跟踪ID，必填
	ChainCode          string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`                            // 区块链名称，如：bitcoin、ethereum、tron，1-36必填
	Bip44Path          string                 `protobuf:"bytes,3,opt,name=bip44_path,json=bip44Path,proto3" json:"bip44_path,omitempty"`                            // BIP-44 路径字符串
	AccountIndexStart  uint32                 `protobuf:"varint,4,opt,name=account_index_start,json=accountIndexStart,proto3" json:"account_index_start,omitempty"` // 账户索引的开始位置，包含当前值；例如：3 表示从 account_index=3 开始派生
	Count              uint32                 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`                                                    // 派生密钥的数量；例如：{account_index_start}=3,{count}=5 表示派生这5个密钥 account_index=3,4,5,6,7
	Bip32KeyCiphertext string                 `protobuf:"bytes,6,opt,name=bip32key_ciphertext,json=bip32keyCiphertext,proto3" json:"bip32key_ciphertext,omitempty"` // 主密钥PEM密文（base64），Genesis返回的seed，必填
	KeyType            string                 `protobuf:"bytes,7,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`                                  // 密钥类型，如ecdsa-secp256k1、ecdsa-secp256r1、eddsa-ed25519，1-36必填
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateKeyRequest) Reset() {
	*x = CreateKeyRequest{}
	mi := &file_proto_keycreator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyRequest) ProtoMessage() {}

func (x *CreateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keycreator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_keycreator_proto_rawDescGZIP(), []int{6}
}

func (x *CreateKeyRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateKeyRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *CreateKeyRequest) GetBip44Path() string {
	if x != nil {
		return x.Bip44Path
	}
	return ""
}

func (x *CreateKeyRequest) GetAccountIndexStart() uint32 {
	if x != nil {
		return x.AccountIndexStart
	}
	return 0
}

func (x *CreateKeyRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CreateKeyRequest) GetBip32KeyCiphertext() string {
	if x != nil {
		return x.Bip32KeyCiphertext
	}
	return ""
}

func (x *CreateKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type CreateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*DerivedChildKey     `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"` // 派生的用户密钥列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyResponse) Reset() {
	*x = CreateKeyResponse{}
	mi := &file_proto_keycreator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyResponse) ProtoMessage() {}

func (x *CreateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keycreator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_keycreator_proto_rawDescGZIP(), []int{7}
}

func (x *CreateKeyResponse) GetKeys() []*DerivedChildKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_proto_keycreator_proto protoreflect.FileDescriptor

const file_proto_keycreator_proto_rawDesc = "" +
	"\n" +
	"\x16proto/keycreator.proto\x12\n" +
	"keycreator\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xbe\x01\n" +
	"\x0eDerivedCoreKey\x12\x1b\n" +
	"\tkey_usage\x18\x01 \x01(\rR\bkeyUsage\x12/\n" +
	"\x13bip32key_ciphertext\x18\x02 \x01(\tR\x12bip32keyCiphertext\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x1d\n" +
	"\n" +
	"bip44_path\x18\x04 \x01(\tR\tbip44Path\x12%\n" +
	"\x0edek_ciphertext\x18\x05 \x01(\tR\rdekCiphertext\"\xe5\x01\n" +
	"\x0fDerivedChildKey\x12.\n" +
	"\x13priv_key_ciphertext\x18\x01 \x01(\tR\x11privKeyCiphertext\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12#\n" +
	"\raddress_index\x18\x03 \x01(\rR\faddressIndex\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x12\x1d\n" +
	"\n" +
	"bip44_path\x18\x05 \x01(\tR\tbip44Path\x12%\n" +
	"\x0edek_ciphertext\x18\x06 \x01(\tR\rdekCiphertext\"e\n" +
	"\x0eGenesisRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x19\n" +
	"\bkey_type\x18\x03 \x01(\tR\akeyType\"\xe1\x01\n" +
	"\x0fGenesisResponse\x12/\n" +
	"\x13bip32key_ciphertext\x18\x01 \x01(\tR\x12bip32keyCiphertext\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x1d\n" +
	"\n" +
	"bip44_path\x18\x03 \x01(\tR\tbip44Path\x12%\n" +
	"\x0edek_ciphertext\x18\x04 \x01(\tR\rdekCiphertext\x12=\n" +
	"\fderived_keys\x18\x05 \x03(\v2\x1a.keycreator.DerivedCoreKeyR\vderivedKeys\"\xfd\x01\n" +
	"\x10CreateKeyRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x1d\n" +
	"\n" +
	"bip44_path\x18\x03 \x01(\tR\tbip44Path\x12.\n" +
	"\x13account_index_start\x18\x04 \x01(\rR\x11accountIndexStart\x12\x14\n" +
	"\x05count\x18\x05 \x01(\rR\x05count\x12/\n" +
	"\x13bip32key_ciphertext\x18\x06 \x01(\tR\x12bip32keyCiphertext\x12\x19\n" +
	"\bkey_type\x18\a \x01(\tR\akeyType\"D\n" +
	"\x11CreateKeyResponse\x12/\n" +
	"\x04keys\x18\x01 \x03(\v2\x1b.keycreator.DerivedChildKeyR\x04keys2\xc3\x02\n" +
	"\n" +
	"KeyCreator\x12N\n" +
	"\vHealthCheck\x12\x1e.keycreator.HealthCheckRequest\x1a\x1f.keycreator.HealthCheckResponse\x12B\n" +
	"\aGenesis\x12\x1a.keycreator.GenesisRequest\x1a\x1b.keycreator.GenesisResponse\x12S\n" +
	"\x14CreateOperationalKey\x12\x1c.keycreator.CreateKeyRequest\x1a\x1d.keycreator.CreateKeyResponse\x12L\n" +
	"\rCreateUserKey\x12\x1c.keycreator.CreateKeyRequest\x1a\x1d.keycreator.CreateKeyResponseB9Z7github.com/koku-web3/go-koku/pkg/proto/key-creator;grpcb\x06proto3"

var (
	file_proto_keycreator_proto_rawDescOnce sync.Once
	file_proto_keycreator_proto_rawDescData []byte
)

func file_proto_keycreator_proto_rawDescGZIP() []byte {
	file_proto_keycreator_proto_rawDescOnce.Do(func() {
		file_proto_keycreator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_keycreator_proto_rawDesc), len(file_proto_keycreator_proto_rawDesc)))
	})
	return file_proto_keycreator_proto_rawDescData
}

var file_proto_keycreator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_keycreator_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: keycreator.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: keycreator.HealthCheckResponse
	(*DerivedCoreKey)(nil),      // 2: keycreator.DerivedCoreKey
	(*DerivedChildKey)(nil),     // 3: keycreator.DerivedChildKey
	(*GenesisRequest)(nil),      // 4: keycreator.GenesisRequest
	(*GenesisResponse)(nil),     // 5: keycreator.GenesisResponse
	(*CreateKeyRequest)(nil),    // 6: keycreator.CreateKeyRequest
	(*CreateKeyResponse)(nil),   // 7: keycreator.CreateKeyResponse
}
var file_proto_keycreator_proto_depIdxs = []int32{
	2, // 0: keycreator.GenesisResponse.derived_keys:type_name -> keycreator.DerivedCoreKey
	3, // 1: keycreator.CreateKeyResponse.keys:type_name -> keycreator.DerivedChildKey
	0, // 2: keycreator.KeyCreator.HealthCheck:input_type -> keycreator.HealthCheckRequest
	4, // 3: keycreator.KeyCreator.Genesis:input_type -> keycreator.GenesisRequest
	6, // 4: keycreator.KeyCreator.CreateOperationalKey:input_type -> keycreator.CreateKeyRequest
	6, // 5: keycreator.KeyCreator.CreateUserKey:input_type -> keycreator.CreateKeyRequest
	1, // 6: keycreator.KeyCreator.HealthCheck:output_type -> keycreator.HealthCheckResponse
	5, // 7: keycreator.KeyCreator.Genesis:output_type -> keycreator.GenesisResponse
	7, // 8: keycreator.KeyCreator.CreateOperationalKey:output_type -> keycreator.CreateKeyResponse
	7, // 9: keycreator.KeyCreator.CreateUserKey:output_type -> keycreator.CreateKeyResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_keycreator_proto_init() }
func file_proto_keycreator_proto_init() {
	if File_proto_keycreator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_keycreator_proto_rawDesc), len(file_proto_keycreator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_keycreator_proto_goTypes,
		DependencyIndexes: file_proto_keycreator_proto_depIdxs,
		MessageInfos:      file_proto_keycreator_proto_msgTypes,
	}.Build()
	File_proto_keycreator_proto = out.File
	file_proto_keycreator_proto_goTypes = nil
	file_proto_keycreator_proto_depIdxs = nil
}
