[grpc]
enable = false   # true: 启用gRPC, false: 启用http
host = "127.0.0.1"
port = 50051

[signer]
address = "127.0.0.1:50052"

[db]
host = ""
port= 3306
user= ""
password= ""
database= ""
max_open_conns= 1000
max_idle_conns= 1000

[log]
rotation = true
file_path = ""
max_size_mb = 100
max_backups = 10
max_age = 30
compress = true
format = "terminal"
verbosity = 3
vmodule = ""
