[grpc]
host = "127.0.0.1"
port = 50051

[vault]
address = "http://127.0.0.1:8200"        # Vault服务器地址
mount_path = "aws"                       # AWS IAM认证挂载路径
role_name = "ethereum-client"            # Vault Role名称
token_refresh_interval = 3500            # Token刷新间隔（秒），必须小于Vault Role的token_ttl，建议设置为token_ttl的80%左右

[aws]
iam_user_enable = true                                             # true: 使用 access_key/secret_key (本地测试), false: 使用 EC2 Instance Profile (生产部署)
access_key = "AKIAU2CJR6GVDDDTGTNR"                                # AWS IAM 用户访问密钥 (仅 iam_user_enable=true 时使用)
secret_key = "ezCHrRiZMuzZ2uWMJYM4iyVdi04ErAOnJAlHjmDp"            # AWS IAM 用户密钥 (仅 iam_user_enable=true 时使用)
role_arn = "arn:aws:iam::330866749866:role/vault@create-key-role"  # Vault Role 绑定的 AWS IAM Role ARN


[log]
rotation = true
file_path = ""
max_size_mb = 100
max_backups = 10
max_age = 30
compress = true
format = "terminal"
verbosity = 3
vmodule = ""
