// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: proto/coordinator.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coordinator_HealthCheck_FullMethodName            = "/coordinator.Coordinator/HealthCheck"
	Coordinator_Genesis_FullMethodName                = "/coordinator.Coordinator/Genesis"
	Coordinator_CreateOperationalKey_FullMethodName   = "/coordinator.Coordinator/CreateOperationalKey"
	Coordinator_CreateUserKey_FullMethodName          = "/coordinator.Coordinator/CreateUserKey"
	Coordinator_VerifyAddress_FullMethodName          = "/coordinator.Coordinator/VerifyAddress"
	Coordinator_VerifyContractAddress_FullMethodName  = "/coordinator.Coordinator/VerifyContractAddress"
	Coordinator_CheckSufficientBalance_FullMethodName = "/coordinator.Coordinator/CheckSufficientBalance"
	Coordinator_UniversalTransfer_FullMethodName      = "/coordinator.Coordinator/UniversalTransfer"
)

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Coordinator gRPC 密钥管理服务
// 作为转发层，将请求转发给 Signer 和 TxBuilder 服务
// 私钥明文仅存在于 Signer 服务内存中
type CoordinatorClient interface {
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 生成核心主密钥
	// 调用 KeyCreator 服务生成 HD 主密钥及其派生的核心密钥
	Genesis(ctx context.Context, in *GenesisRequest, opts ...grpc.CallOption) (*GenesisResponse, error)
	// 创建运营密钥
	CreateOperationalKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error)
	// 创建用户密钥
	CreateUserKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error)
	// 校验地址是否合法
	VerifyAddress(ctx context.Context, in *VerifyAddressRequest, opts ...grpc.CallOption) (*VerifyAddressResponse, error)
	// 校验合约地址是否合法
	VerifyContractAddress(ctx context.Context, in *VerifyContractAddressRequest, opts ...grpc.CallOption) (*VerifyContractAddressResponse, error)
	// 检查地址是否有足够的余额转账
	// 支持检查合约余额
	CheckSufficientBalance(ctx context.Context, in *CheckSufficientBalanceRequest, opts ...grpc.CallOption) (*CheckSufficientBalanceResponse, error)
	// 通用转账
	// 非UTXO，具有出账地址、入账地址、金额、合约地址等普遍通用的转账
	UniversalTransfer(ctx context.Context, in *UniversalTransferRequest, opts ...grpc.CallOption) (*UniversalTransferResponse, error)
}

type coordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorClient(cc grpc.ClientConnInterface) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Coordinator_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) Genesis(ctx context.Context, in *GenesisRequest, opts ...grpc.CallOption) (*GenesisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenesisResponse)
	err := c.cc.Invoke(ctx, Coordinator_Genesis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) CreateOperationalKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyResponse)
	err := c.cc.Invoke(ctx, Coordinator_CreateOperationalKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) CreateUserKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyResponse)
	err := c.cc.Invoke(ctx, Coordinator_CreateUserKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) VerifyAddress(ctx context.Context, in *VerifyAddressRequest, opts ...grpc.CallOption) (*VerifyAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAddressResponse)
	err := c.cc.Invoke(ctx, Coordinator_VerifyAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) VerifyContractAddress(ctx context.Context, in *VerifyContractAddressRequest, opts ...grpc.CallOption) (*VerifyContractAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyContractAddressResponse)
	err := c.cc.Invoke(ctx, Coordinator_VerifyContractAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) CheckSufficientBalance(ctx context.Context, in *CheckSufficientBalanceRequest, opts ...grpc.CallOption) (*CheckSufficientBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSufficientBalanceResponse)
	err := c.cc.Invoke(ctx, Coordinator_CheckSufficientBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) UniversalTransfer(ctx context.Context, in *UniversalTransferRequest, opts ...grpc.CallOption) (*UniversalTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniversalTransferResponse)
	err := c.cc.Invoke(ctx, Coordinator_UniversalTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
// All implementations must embed UnimplementedCoordinatorServer
// for forward compatibility.
//
// Coordinator gRPC 密钥管理服务
// 作为转发层，将请求转发给 Signer 和 TxBuilder 服务
// 私钥明文仅存在于 Signer 服务内存中
type CoordinatorServer interface {
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 生成核心主密钥
	// 调用 KeyCreator 服务生成 HD 主密钥及其派生的核心密钥
	Genesis(context.Context, *GenesisRequest) (*GenesisResponse, error)
	// 创建运营密钥
	CreateOperationalKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error)
	// 创建用户密钥
	CreateUserKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error)
	// 校验地址是否合法
	VerifyAddress(context.Context, *VerifyAddressRequest) (*VerifyAddressResponse, error)
	// 校验合约地址是否合法
	VerifyContractAddress(context.Context, *VerifyContractAddressRequest) (*VerifyContractAddressResponse, error)
	// 检查地址是否有足够的余额转账
	// 支持检查合约余额
	CheckSufficientBalance(context.Context, *CheckSufficientBalanceRequest) (*CheckSufficientBalanceResponse, error)
	// 通用转账
	// 非UTXO，具有出账地址、入账地址、金额、合约地址等普遍通用的转账
	UniversalTransfer(context.Context, *UniversalTransferRequest) (*UniversalTransferResponse, error)
	mustEmbedUnimplementedCoordinatorServer()
}

// UnimplementedCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServer struct{}

func (UnimplementedCoordinatorServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCoordinatorServer) Genesis(context.Context, *GenesisRequest) (*GenesisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Genesis not implemented")
}
func (UnimplementedCoordinatorServer) CreateOperationalKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOperationalKey not implemented")
}
func (UnimplementedCoordinatorServer) CreateUserKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserKey not implemented")
}
func (UnimplementedCoordinatorServer) VerifyAddress(context.Context, *VerifyAddressRequest) (*VerifyAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAddress not implemented")
}
func (UnimplementedCoordinatorServer) VerifyContractAddress(context.Context, *VerifyContractAddressRequest) (*VerifyContractAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyContractAddress not implemented")
}
func (UnimplementedCoordinatorServer) CheckSufficientBalance(context.Context, *CheckSufficientBalanceRequest) (*CheckSufficientBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSufficientBalance not implemented")
}
func (UnimplementedCoordinatorServer) UniversalTransfer(context.Context, *UniversalTransferRequest) (*UniversalTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UniversalTransfer not implemented")
}
func (UnimplementedCoordinatorServer) mustEmbedUnimplementedCoordinatorServer() {}
func (UnimplementedCoordinatorServer) testEmbeddedByValue()                     {}

// UnsafeCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServer will
// result in compilation errors.
type UnsafeCoordinatorServer interface {
	mustEmbedUnimplementedCoordinatorServer()
}

func RegisterCoordinatorServer(s grpc.ServiceRegistrar, srv CoordinatorServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coordinator_ServiceDesc, srv)
}

func _Coordinator_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_Genesis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenesisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).Genesis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_Genesis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).Genesis(ctx, req.(*GenesisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_CreateOperationalKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).CreateOperationalKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_CreateOperationalKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).CreateOperationalKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_CreateUserKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).CreateUserKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_CreateUserKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).CreateUserKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_VerifyAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).VerifyAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_VerifyAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).VerifyAddress(ctx, req.(*VerifyAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_VerifyContractAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyContractAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).VerifyContractAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_VerifyContractAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).VerifyContractAddress(ctx, req.(*VerifyContractAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_CheckSufficientBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSufficientBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).CheckSufficientBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_CheckSufficientBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).CheckSufficientBalance(ctx, req.(*CheckSufficientBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_UniversalTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniversalTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).UniversalTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_UniversalTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).UniversalTransfer(ctx, req.(*UniversalTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Coordinator_ServiceDesc is the grpc.ServiceDesc for Coordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordinator.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Coordinator_HealthCheck_Handler,
		},
		{
			MethodName: "Genesis",
			Handler:    _Coordinator_Genesis_Handler,
		},
		{
			MethodName: "CreateOperationalKey",
			Handler:    _Coordinator_CreateOperationalKey_Handler,
		},
		{
			MethodName: "CreateUserKey",
			Handler:    _Coordinator_CreateUserKey_Handler,
		},
		{
			MethodName: "VerifyAddress",
			Handler:    _Coordinator_VerifyAddress_Handler,
		},
		{
			MethodName: "VerifyContractAddress",
			Handler:    _Coordinator_VerifyContractAddress_Handler,
		},
		{
			MethodName: "CheckSufficientBalance",
			Handler:    _Coordinator_CheckSufficientBalance_Handler,
		},
		{
			MethodName: "UniversalTransfer",
			Handler:    _Coordinator_UniversalTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coordinator.proto",
}
