// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/coordinator.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GenesisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`       // 链路跟踪 ID，1-36 必填
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"` // 区块链代码，1-36 必填
	KeyType       string                 `protobuf:"bytes,3,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`       // 密钥类型，如ecdsa-secp256k1、ecdsa-secp256r1、eddsa-ed25519，1-36必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisRequest) Reset() {
	*x = GenesisRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisRequest) ProtoMessage() {}

func (x *GenesisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisRequest.ProtoReflect.Descriptor instead.
func (*GenesisRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *GenesisRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GenesisRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *GenesisRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type GenesisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 执行结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisResponse) Reset() {
	*x = GenesisResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisResponse) ProtoMessage() {}

func (x *GenesisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisResponse.ProtoReflect.Descriptor instead.
func (*GenesisResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *GenesisResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`       // 链路跟踪 ID，1-36 必填
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"` // 区块链代码，1-36 必填
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                         // 生成密钥数量，范围 1-50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyRequest) Reset() {
	*x = CreateKeyRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyRequest) ProtoMessage() {}

func (x *CreateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *CreateKeyRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateKeyRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *CreateKeyRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                           // 执行结果
	AddressList   []*AddressInfo         `protobuf:"bytes,2,rep,name=address_list,json=addressList,proto3" json:"address_list,omitempty"` // 地址列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyResponse) Reset() {
	*x = CreateKeyResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyResponse) ProtoMessage() {}

func (x *CreateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *CreateKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateKeyResponse) GetAddressList() []*AddressInfo {
	if x != nil {
		return x.AddressList
	}
	return nil
}

type AddressInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIndex  uint32                 `protobuf:"varint,1,opt,name=account_index,json=accountIndex,proto3" json:"account_index,omitempty"` // 账户索引
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                // 区块链地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInfo) Reset() {
	*x = AddressInfo{}
	mi := &file_proto_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfo) ProtoMessage() {}

func (x *AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfo.ProtoReflect.Descriptor instead.
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *AddressInfo) GetAccountIndex() uint32 {
	if x != nil {
		return x.AccountIndex
	}
	return 0
}

func (x *AddressInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type VerifyAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ChainCode     string                 `protobuf:"bytes,3,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAddressRequest) Reset() {
	*x = VerifyAddressRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAddressRequest) ProtoMessage() {}

func (x *VerifyAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAddressRequest.ProtoReflect.Descriptor instead.
func (*VerifyAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyAddressRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *VerifyAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VerifyAddressRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

type VerifyAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAddressResponse) Reset() {
	*x = VerifyAddressResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAddressResponse) ProtoMessage() {}

func (x *VerifyAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAddressResponse.ProtoReflect.Descriptor instead.
func (*VerifyAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyAddressResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type VerifyContractAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ChainCode     string                 `protobuf:"bytes,3,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyContractAddressRequest) Reset() {
	*x = VerifyContractAddressRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyContractAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyContractAddressRequest) ProtoMessage() {}

func (x *VerifyContractAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyContractAddressRequest.ProtoReflect.Descriptor instead.
func (*VerifyContractAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyContractAddressRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *VerifyContractAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VerifyContractAddressRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

type VerifyContractAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyContractAddressResponse) Reset() {
	*x = VerifyContractAddressResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyContractAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyContractAddressResponse) ProtoMessage() {}

func (x *VerifyContractAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyContractAddressResponse.ProtoReflect.Descriptor instead.
func (*VerifyContractAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyContractAddressResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type CheckSufficientBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`             // 1-36 必填
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`       // 1-36 必填； 唯一， 表示区块链名称，如：bitcoin、ethereum、tron
	Coin          string                 `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin,omitempty"`                                  // 必填； 唯一， 表示转账币种，如：btc、eth、usdt、dog；不涉及判断逻辑，仅作展示
	FromAddress   string                 `protobuf:"bytes,4,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"` // 1-256 必填；转账发起地址
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`                              // 必填； 金额，单位是最小该链单位，如：以太坊单位就是wei；波场单位就是sun
	Contract      string                 `protobuf:"bytes,6,opt,name=contract,proto3" json:"contract,omitempty"`                          // 1-256 非必填；转账币种对应的合约地址。如果空串表示主链币
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSufficientBalanceRequest) Reset() {
	*x = CheckSufficientBalanceRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSufficientBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSufficientBalanceRequest) ProtoMessage() {}

func (x *CheckSufficientBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSufficientBalanceRequest.ProtoReflect.Descriptor instead.
func (*CheckSufficientBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *CheckSufficientBalanceRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CheckSufficientBalanceRequest) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

type CheckSufficientBalanceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsCoinSufficient  bool                   `protobuf:"varint,1,opt,name=is_coin_sufficient,json=isCoinSufficient,proto3" json:"is_coin_sufficient,omitempty"`    // 主链币是否足够
	IsTokenSufficient bool                   `protobuf:"varint,2,opt,name=is_token_sufficient,json=isTokenSufficient,proto3" json:"is_token_sufficient,omitempty"` // 合约余额是否足够；注意当检查合约余额时两个返回值都需要判断
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckSufficientBalanceResponse) Reset() {
	*x = CheckSufficientBalanceResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSufficientBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSufficientBalanceResponse) ProtoMessage() {}

func (x *CheckSufficientBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSufficientBalanceResponse.ProtoReflect.Descriptor instead.
func (*CheckSufficientBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{12}
}

func (x *CheckSufficientBalanceResponse) GetIsCoinSufficient() bool {
	if x != nil {
		return x.IsCoinSufficient
	}
	return false
}

func (x *CheckSufficientBalanceResponse) GetIsTokenSufficient() bool {
	if x != nil {
		return x.IsTokenSufficient
	}
	return false
}

type UniversalTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`             // 1-36 必填
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`       // 1-36 必填； 唯一， 表示区块链名称，如：bitcoin、ethereum、tron
	Coin          string                 `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin,omitempty"`                                  // 必填； 唯一， 表示转账币种，如：btc、eth、usdt、dog；不涉及判断逻辑，仅作展示
	FromAddress   string                 `protobuf:"bytes,4,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"` // 1-256 必填；转账发起地址
	ToAddress     string                 `protobuf:"bytes,5,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`       // 1-256 必填；转账接收地址
	Amount        string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`                              // 必填； 金额，单位是最小该链单位，如：以太坊单位就是wei；波场单位就是sun
	Contract      string                 `protobuf:"bytes,7,opt,name=contract,proto3" json:"contract,omitempty"`                          // 1-256 非必填；转账币种对应的合约地址。如果空串表示主链币
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniversalTransferRequest) Reset() {
	*x = UniversalTransferRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniversalTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalTransferRequest) ProtoMessage() {}

func (x *UniversalTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversalTransferRequest.ProtoReflect.Descriptor instead.
func (*UniversalTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{13}
}

func (x *UniversalTransferRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *UniversalTransferRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *UniversalTransferRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *UniversalTransferRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *UniversalTransferRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *UniversalTransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UniversalTransferRequest) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

type UniversalTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"` // 已处理
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniversalTransferResponse) Reset() {
	*x = UniversalTransferResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniversalTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalTransferResponse) ProtoMessage() {}

func (x *UniversalTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversalTransferResponse.ProtoReflect.Descriptor instead.
func (*UniversalTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{14}
}

func (x *UniversalTransferResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_coordinator_proto protoreflect.FileDescriptor

const file_proto_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x17proto/coordinator.proto\x12\vcoordinator\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"e\n" +
	"\x0eGenesisRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x19\n" +
	"\bkey_type\x18\x03 \x01(\tR\akeyType\"+\n" +
	"\x0fGenesisResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"b\n" +
	"\x10CreateKeyRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"j\n" +
	"\x11CreateKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12;\n" +
	"\faddress_list\x18\x02 \x03(\v2\x18.coordinator.AddressInfoR\vaddressList\"L\n" +
	"\vAddressInfo\x12#\n" +
	"\raccount_index\x18\x01 \x01(\rR\faccountIndex\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"j\n" +
	"\x14VerifyAddressRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x03 \x01(\tR\tchainCode\"2\n" +
	"\x15VerifyAddressResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"r\n" +
	"\x1cVerifyContractAddressRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x03 \x01(\tR\tchainCode\":\n" +
	"\x1dVerifyContractAddressResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"\xc4\x01\n" +
	"\x1dCheckSufficientBalanceRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x12\n" +
	"\x04coin\x18\x03 \x01(\tR\x04coin\x12!\n" +
	"\ffrom_address\x18\x04 \x01(\tR\vfromAddress\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcontract\x18\x06 \x01(\tR\bcontract\"~\n" +
	"\x1eCheckSufficientBalanceResponse\x12,\n" +
	"\x12is_coin_sufficient\x18\x01 \x01(\bR\x10isCoinSufficient\x12.\n" +
	"\x13is_token_sufficient\x18\x02 \x01(\bR\x11isTokenSufficient\"\xde\x01\n" +
	"\x18UniversalTransferRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x12\n" +
	"\x04coin\x18\x03 \x01(\tR\x04coin\x12!\n" +
	"\ffrom_address\x18\x04 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x05 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcontract\x18\a \x01(\tR\bcontract\"+\n" +
	"\x19UniversalTransferResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xeb\x05\n" +
	"\vCoordinator\x12P\n" +
	"\vHealthCheck\x12\x1f.coordinator.HealthCheckRequest\x1a .coordinator.HealthCheckResponse\x12D\n" +
	"\aGenesis\x12\x1b.coordinator.GenesisRequest\x1a\x1c.coordinator.GenesisResponse\x12U\n" +
	"\x14CreateOperationalKey\x12\x1d.coordinator.CreateKeyRequest\x1a\x1e.coordinator.CreateKeyResponse\x12N\n" +
	"\rCreateUserKey\x12\x1d.coordinator.CreateKeyRequest\x1a\x1e.coordinator.CreateKeyResponse\x12V\n" +
	"\rVerifyAddress\x12!.coordinator.VerifyAddressRequest\x1a\".coordinator.VerifyAddressResponse\x12n\n" +
	"\x15VerifyContractAddress\x12).coordinator.VerifyContractAddressRequest\x1a*.coordinator.VerifyContractAddressResponse\x12q\n" +
	"\x16CheckSufficientBalance\x12*.coordinator.CheckSufficientBalanceRequest\x1a+.coordinator.CheckSufficientBalanceResponse\x12b\n" +
	"\x11UniversalTransfer\x12%.coordinator.UniversalTransferRequest\x1a&.coordinator.UniversalTransferResponseB9Z7github.com/koku-web3/go-koku/pkg/proto/coordinator;grpcb\x06proto3"

var (
	file_proto_coordinator_proto_rawDescOnce sync.Once
	file_proto_coordinator_proto_rawDescData []byte
)

func file_proto_coordinator_proto_rawDescGZIP() []byte {
	file_proto_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)))
	})
	return file_proto_coordinator_proto_rawDescData
}

var file_proto_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_coordinator_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),             // 0: coordinator.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 1: coordinator.HealthCheckResponse
	(*GenesisRequest)(nil),                 // 2: coordinator.GenesisRequest
	(*GenesisResponse)(nil),                // 3: coordinator.GenesisResponse
	(*CreateKeyRequest)(nil),               // 4: coordinator.CreateKeyRequest
	(*CreateKeyResponse)(nil),              // 5: coordinator.CreateKeyResponse
	(*AddressInfo)(nil),                    // 6: coordinator.AddressInfo
	(*VerifyAddressRequest)(nil),           // 7: coordinator.VerifyAddressRequest
	(*VerifyAddressResponse)(nil),          // 8: coordinator.VerifyAddressResponse
	(*VerifyContractAddressRequest)(nil),   // 9: coordinator.VerifyContractAddressRequest
	(*VerifyContractAddressResponse)(nil),  // 10: coordinator.VerifyContractAddressResponse
	(*CheckSufficientBalanceRequest)(nil),  // 11: coordinator.CheckSufficientBalanceRequest
	(*CheckSufficientBalanceResponse)(nil), // 12: coordinator.CheckSufficientBalanceResponse
	(*UniversalTransferRequest)(nil),       // 13: coordinator.UniversalTransferRequest
	(*UniversalTransferResponse)(nil),      // 14: coordinator.UniversalTransferResponse
}
var file_proto_coordinator_proto_depIdxs = []int32{
	6,  // 0: coordinator.CreateKeyResponse.address_list:type_name -> coordinator.AddressInfo
	0,  // 1: coordinator.Coordinator.HealthCheck:input_type -> coordinator.HealthCheckRequest
	2,  // 2: coordinator.Coordinator.Genesis:input_type -> coordinator.GenesisRequest
	4,  // 3: coordinator.Coordinator.CreateOperationalKey:input_type -> coordinator.CreateKeyRequest
	4,  // 4: coordinator.Coordinator.CreateUserKey:input_type -> coordinator.CreateKeyRequest
	7,  // 5: coordinator.Coordinator.VerifyAddress:input_type -> coordinator.VerifyAddressRequest
	9,  // 6: coordinator.Coordinator.VerifyContractAddress:input_type -> coordinator.VerifyContractAddressRequest
	11, // 7: coordinator.Coordinator.CheckSufficientBalance:input_type -> coordinator.CheckSufficientBalanceRequest
	13, // 8: coordinator.Coordinator.UniversalTransfer:input_type -> coordinator.UniversalTransferRequest
	1,  // 9: coordinator.Coordinator.HealthCheck:output_type -> coordinator.HealthCheckResponse
	3,  // 10: coordinator.Coordinator.Genesis:output_type -> coordinator.GenesisResponse
	5,  // 11: coordinator.Coordinator.CreateOperationalKey:output_type -> coordinator.CreateKeyResponse
	5,  // 12: coordinator.Coordinator.CreateUserKey:output_type -> coordinator.CreateKeyResponse
	8,  // 13: coordinator.Coordinator.VerifyAddress:output_type -> coordinator.VerifyAddressResponse
	10, // 14: coordinator.Coordinator.VerifyContractAddress:output_type -> coordinator.VerifyContractAddressResponse
	12, // 15: coordinator.Coordinator.CheckSufficientBalance:output_type -> coordinator.CheckSufficientBalanceResponse
	14, // 16: coordinator.Coordinator.UniversalTransfer:output_type -> coordinator.UniversalTransferResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_coordinator_proto_init() }
func file_proto_coordinator_proto_init() {
	if File_proto_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_proto_depIdxs,
		MessageInfos:      file_proto_coordinator_proto_msgTypes,
	}.Build()
	File_proto_coordinator_proto = out.File
	file_proto_coordinator_proto_goTypes = nil
	file_proto_coordinator_proto_depIdxs = nil
}
