syntax = "proto3";

package keycreator;

option go_package = "github.com/koku-web3/go-koku/pkg/proto/key-creator;grpc";

service KeyCreator {
  // 健康检查
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse);
  // 生成核心主密钥
  rpc Genesis(GenesisRequest) returns (GenesisResponse);
  // 创建运营密钥
  rpc CreateOperationalKey(CreateKeyRequest) returns (CreateKeyResponse);
  // 创建用户密钥
  rpc CreateUserKey(CreateKeyRequest) returns (CreateKeyResponse);
}

// ============ 健康检查 ============

message HealthCheckRequest {}

message HealthCheckResponse {
  string status = 1;
}



// 派生的密钥数据
message DerivedCoreKey {
  uint32 key_usage = 1; //0：运营密钥进行签名；场景：归集、出账；1：用户密钥进行签名出账；场景：归集
  string bip32key_ciphertext = 2; // 加密后的bip32主密钥 hex 格式
  string context = 3; // 密钥派生上下文标识符，1-36必填，唯一；在 vault 系统加解密时使用；格式类似：m-44-60-0-0-0
  string bip44_path = 4; // BIP-44 路径字符串
  string dek_ciphertext = 5; // DEK 数据加密密钥，用于信封加密
}

message DerivedChildKey {
  string priv_key_ciphertext = 1; // 加密后的 DER 格式密钥，返回base64编码格式
  string public_key = 2; // PKIX格式公钥（使用 ASN.1 数据结构，DER 编码）；返回 PEM 文本格式
  uint32 address_index = 3; // 地址索引
  string context = 4; // 密钥派生上下文标识符，1-36必填，唯一；在 vault 系统加解密时使用；格式类似：m-44-60-0-0-0
  string bip44_path = 5; // BIP-44 路径字符串
  string dek_ciphertext = 6; // DEK 数据加密密钥，用于信封加密
}

// ============ 生成核心主密钥 ============

message GenesisRequest {
  string trace_id = 1; // 链路跟踪ID，必填
  string chain_code = 2; // 区块链名称，如：bitcoin、ethereum、tron，1-36必填
  string key_type = 3; // 密钥类型，如ecdsa-secp256k1、ecdsa-secp256r1、eddsa-ed25519，1-36必填
}

message GenesisResponse {
  string seed_ciphertext = 1; // HD seed 经 Vault 信封加密后的密文
  string context = 2; // 密钥派生上下文标识符，1-36必填，唯一；在 vault 系统加解密时使用；格式类似：m-44-60-0-0-0
  string bip44_path = 3; // BIP-44 路径字符串
  string dek_ciphertext = 4; // DEK 数据加密密钥，用于信封加密
  repeated DerivedCoreKey derived_keys = 5; // 派生的密钥列表 (运营账户和用户账户)
}


// ============ 创建派生密钥 ============

message CreateKeyRequest {
  string trace_id = 1; // 链路跟踪ID，必填
  string chain_code = 2; // 区块链名称，如：bitcoin、ethereum、tron，1-36必填
  string bip44_path = 3; // BIP-44 路径字符串
  uint32 account_index_start = 4; // 账户索引的开始位置，包含当前值；例如：3 表示从 account_index=3 开始派生
  uint32 count = 5; // 派生密钥的数量；例如：{account_index_start}=3,{count}=5 表示派生这5个密钥 account_index=3,4,5,6,7 
  string bip32key_ciphertext = 6; // 主密钥PEM密文（base64），Genesis返回的seed，必填
  string key_type = 7; // 密钥类型，如ecdsa-secp256k1、ecdsa-secp256r1、eddsa-ed25519，1-36必填
}

message CreateKeyResponse {
  repeated DerivedChildKey keys = 1; // 派生的用户密钥列表
}



