syntax = "proto3";

package signer;

// 前面的路径：告诉 protoc-gen-go 生成的 pb.go 文件放到/对应..proto/signer目录
// 后面的路径：生成的 package 名称为 signer
option go_package = "github.com/koku-web3/go-koku/pkg/proto/signer;signer";

// Signer 服务
service Signer {
  // 健康检查
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse);
  // 使用 BIP44 路径 Account=0(运营密钥) 的子密钥签名消息
  // 场景：归集、出账
  rpc SignAcct0(SignRequest) returns (SignResponse);
  // 使用 BIP44 路径 Account=1(用户密钥) 的子密钥签名消息
  // 场景：归集
  rpc SignAcct1(SignRequest) returns (SignResponse);
}

// ============ 健康检查 ============

message HealthCheckRequest {}

message HealthCheckResponse {
  string status = 1;
}

// ============ 消息签名 ============

// 签名请求
message SignRequest {
  string trace_id = 1; // 链路跟踪ID，必填
  string chain_code = 2; // 区块链名称，1-36必填
  string bip44_path = 3; // BIP-44路径，格式：m/44'/60'/0'/0/0
  string key_type = 4; // 密钥类型，如ecdsa-secp256k1、ecdsa-secp256r1、eddsa-ed25519，1-36必填
  string message = 5; // 待签名数据，1-1024必填
  string priv_key_ciphertext = 6; // 私钥密文，1-1024必填
}

// 签名响应
message SignResponse {
  string signature = 1; // 已签名数据，返回 hex 格式
}


