// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/signer.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建主密钥请求
type CreateMasterKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`       // 链路跟踪ID，必填
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"` // 区块链名称，如：bitcoin、ethereum、tron，1-36必填
	KeyType       string                 `protobuf:"bytes,3,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`       // 密钥类型，如ecdsa-secp256k1、ecdsa-secp256r1、eddsa-ed25519，1-36必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMasterKeyRequest) Reset() {
	*x = CreateMasterKeyRequest{}
	mi := &file_proto_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterKeyRequest) ProtoMessage() {}

func (x *CreateMasterKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateMasterKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMasterKeyRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateMasterKeyRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *CreateMasterKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

// 创建主密钥响应
type CreateMasterKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyName       string                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"` // 主密钥名称
	Seed          string                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`                      // 主密钥种子（base64），用于备份
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMasterKeyResponse) Reset() {
	*x = CreateMasterKeyResponse{}
	mi := &file_proto_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterKeyResponse) ProtoMessage() {}

func (x *CreateMasterKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateMasterKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMasterKeyResponse) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *CreateMasterKeyResponse) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

// 创建密钥请求
type CreateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                     // 链路跟踪ID，必填
	ChainCode     string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`               // 区块链名称，如：bitcoin、ethereum、tron，1-36必填
	MasterKeyName string                 `protobuf:"bytes,3,opt,name=master_key_name,json=masterKeyName,proto3" json:"master_key_name,omitempty"` // 主密钥名称，1-36必填，唯一
	KeyContext    string                 `protobuf:"bytes,4,opt,name=key_context,json=keyContext,proto3" json:"key_context,omitempty"`            // 密钥派生上下文标识符，1-36必填，唯一
	KeyType       string                 `protobuf:"bytes,5,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`                     // 密钥类型，如ecdsa-secp256k1、ecdsa-secp256r1、eddsa-ed25519，1-36必填
	// BIP-44 派生路径参数
	Account       uint32 `protobuf:"varint,6,opt,name=account,proto3" json:"account,omitempty"`                               // 账户索引，默认 0
	Change        uint32 `protobuf:"varint,7,opt,name=change,proto3" json:"change,omitempty"`                                 // 0=外部链，1=内部链，默认 0
	AddressIndex  uint32 `protobuf:"varint,8,opt,name=address_index,json=addressIndex,proto3" json:"address_index,omitempty"` // 地址索引，默认 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyRequest) Reset() {
	*x = CreateKeyRequest{}
	mi := &file_proto_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyRequest) ProtoMessage() {}

func (x *CreateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKeyRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateKeyRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *CreateKeyRequest) GetMasterKeyName() string {
	if x != nil {
		return x.MasterKeyName
	}
	return ""
}

func (x *CreateKeyRequest) GetKeyContext() string {
	if x != nil {
		return x.KeyContext
	}
	return ""
}

func (x *CreateKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *CreateKeyRequest) GetAccount() uint32 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *CreateKeyRequest) GetChange() uint32 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *CreateKeyRequest) GetAddressIndex() uint32 {
	if x != nil {
		return x.AddressIndex
	}
	return 0
}

// 创建密钥响应
type CreateKeyResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PrivKeyCiphertext string                 `protobuf:"bytes,1,opt,name=priv_key_ciphertext,json=privKeyCiphertext,proto3" json:"priv_key_ciphertext,omitempty"` // 加密后的私钥，base64格式
	PublicKey         string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                           // 公钥，base64格式
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateKeyResponse) Reset() {
	*x = CreateKeyResponse{}
	mi := &file_proto_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyResponse) ProtoMessage() {}

func (x *CreateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{3}
}

func (x *CreateKeyResponse) GetPrivKeyCiphertext() string {
	if x != nil {
		return x.PrivKeyCiphertext
	}
	return ""
}

func (x *CreateKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// 签名请求
type SignRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TraceId           string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                 // 链路跟踪ID，必填
	ChainCode         string                 `protobuf:"bytes,2,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`                           // 区块链名称，1-36必填
	MasterKeyName     string                 `protobuf:"bytes,3,opt,name=master_key_name,json=masterKeyName,proto3" json:"master_key_name,omitempty"`             // 主密钥名称，1-36必填
	KeyContext        string                 `protobuf:"bytes,4,opt,name=key_context,json=keyContext,proto3" json:"key_context,omitempty"`                        // 密钥派生上下文标识符，1-36必填
	KeyType           string                 `protobuf:"bytes,5,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`                                 // 密钥类型，1-36必填
	Message           string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                                                // 待签名数据，1-1024必填
	PrivKeyCiphertext string                 `protobuf:"bytes,7,opt,name=priv_key_ciphertext,json=privKeyCiphertext,proto3" json:"priv_key_ciphertext,omitempty"` // 私钥密文，1-1024必填
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_proto_signer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{4}
}

func (x *SignRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SignRequest) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *SignRequest) GetMasterKeyName() string {
	if x != nil {
		return x.MasterKeyName
	}
	return ""
}

func (x *SignRequest) GetKeyContext() string {
	if x != nil {
		return x.KeyContext
	}
	return ""
}

func (x *SignRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *SignRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignRequest) GetPrivKeyCiphertext() string {
	if x != nil {
		return x.PrivKeyCiphertext
	}
	return ""
}

// 签名响应
type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"` // 已签名数据，base64格式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_proto_signer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{5}
}

func (x *SignResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_proto_signer_proto protoreflect.FileDescriptor

const file_proto_signer_proto_rawDesc = "" +
	"\n" +
	"\x12proto/signer.proto\x12\x06signer\"m\n" +
	"\x16CreateMasterKeyRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12\x19\n" +
	"\bkey_type\x18\x03 \x01(\tR\akeyType\"H\n" +
	"\x17CreateMasterKeyResponse\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\tR\x04seed\"\x87\x02\n" +
	"\x10CreateKeyRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12&\n" +
	"\x0fmaster_key_name\x18\x03 \x01(\tR\rmasterKeyName\x12\x1f\n" +
	"\vkey_context\x18\x04 \x01(\tR\n" +
	"keyContext\x12\x19\n" +
	"\bkey_type\x18\x05 \x01(\tR\akeyType\x12\x18\n" +
	"\aaccount\x18\x06 \x01(\rR\aaccount\x12\x16\n" +
	"\x06change\x18\a \x01(\rR\x06change\x12#\n" +
	"\raddress_index\x18\b \x01(\rR\faddressIndex\"b\n" +
	"\x11CreateKeyResponse\x12.\n" +
	"\x13priv_key_ciphertext\x18\x01 \x01(\tR\x11privKeyCiphertext\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"\xf5\x01\n" +
	"\vSignRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"chain_code\x18\x02 \x01(\tR\tchainCode\x12&\n" +
	"\x0fmaster_key_name\x18\x03 \x01(\tR\rmasterKeyName\x12\x1f\n" +
	"\vkey_context\x18\x04 \x01(\tR\n" +
	"keyContext\x12\x19\n" +
	"\bkey_type\x18\x05 \x01(\tR\akeyType\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12.\n" +
	"\x13priv_key_ciphertext\x18\a \x01(\tR\x11privKeyCiphertext\",\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature2\xd1\x01\n" +
	"\x06Signer\x12R\n" +
	"\x0fCreateMasterKey\x12\x1e.signer.CreateMasterKeyRequest\x1a\x1f.signer.CreateMasterKeyResponse\x12@\n" +
	"\tCreateKey\x12\x18.signer.CreateKeyRequest\x1a\x19.signer.CreateKeyResponse\x121\n" +
	"\x04Sign\x12\x13.signer.SignRequest\x1a\x14.signer.SignResponseB\x06Z\x04grpcb\x06proto3"

var (
	file_proto_signer_proto_rawDescOnce sync.Once
	file_proto_signer_proto_rawDescData []byte
)

func file_proto_signer_proto_rawDescGZIP() []byte {
	file_proto_signer_proto_rawDescOnce.Do(func() {
		file_proto_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signer_proto_rawDesc), len(file_proto_signer_proto_rawDesc)))
	})
	return file_proto_signer_proto_rawDescData
}

var file_proto_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_signer_proto_goTypes = []any{
	(*CreateMasterKeyRequest)(nil),  // 0: signer.CreateMasterKeyRequest
	(*CreateMasterKeyResponse)(nil), // 1: signer.CreateMasterKeyResponse
	(*CreateKeyRequest)(nil),        // 2: signer.CreateKeyRequest
	(*CreateKeyResponse)(nil),       // 3: signer.CreateKeyResponse
	(*SignRequest)(nil),             // 4: signer.SignRequest
	(*SignResponse)(nil),            // 5: signer.SignResponse
}
var file_proto_signer_proto_depIdxs = []int32{
	0, // 0: signer.Signer.CreateMasterKey:input_type -> signer.CreateMasterKeyRequest
	2, // 1: signer.Signer.CreateKey:input_type -> signer.CreateKeyRequest
	4, // 2: signer.Signer.Sign:input_type -> signer.SignRequest
	1, // 3: signer.Signer.CreateMasterKey:output_type -> signer.CreateMasterKeyResponse
	3, // 4: signer.Signer.CreateKey:output_type -> signer.CreateKeyResponse
	5, // 5: signer.Signer.Sign:output_type -> signer.SignResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_signer_proto_init() }
func file_proto_signer_proto_init() {
	if File_proto_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signer_proto_rawDesc), len(file_proto_signer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_signer_proto_goTypes,
		DependencyIndexes: file_proto_signer_proto_depIdxs,
		MessageInfos:      file_proto_signer_proto_msgTypes,
	}.Build()
	File_proto_signer_proto = out.File
	file_proto_signer_proto_goTypes = nil
	file_proto_signer_proto_depIdxs = nil
}
