# ------------------------------------------------------------------
# 项目名称（project）：作为容器名前缀（kms-vault-1、kms-vault-2、kms-vault-3）
# ------------------------------------------------------------------
name: kms

services:
  # ==================================================================
  # 基础模板服务（不会真正启动，只是被下面 3 个节点 extends 复用配置）
  # ==================================================================
  vault-base:
    volumes:
      - ./local-config/hcl:/vault/config/hcl:ro
      - ./local-config/policy:/vault/config/policy:ro
      - ./local-config/certs:/vault/certs:ro
      - ./local-config/encryption:/vault/encryption:ro
    env_file:
      - path: ./vault.env # 引入公共环境变量
        required: true
    networks:
      - vault_cluster # 加入集群共享网络
    build:
      context: . # 构建上下文目录（当前 compose 文件所在目录，即 vault-deploy/）
      dockerfile: vault.Dockerfile # 使用的 Dockerfile 文件名
    environment:
      VAULT_CACERT: "/vault/certs/ca.pem" # 需要设置环境变量指定证书机构, 否则报错：tls: failed to verify certificate: x509: certificate signed by unknown authority

  # ==================================================================
  # 节点 1：集群第一个节点
  # ==================================================================
  vault-1:
    extends:
      service: vault-base # 继承 vault-base 的 volumes/env_file/networks/build 配置
    container_name: kms-vault-1 # 容器名（其他节点靠这个名字通过网络访问它）
    hostname: kms-vault-1 # 容器内部主机名, 同时也是集群内其他节点 retry_join 时用到的地址
    volumes:
      # bind mount: 节点 1 的 Raft 数据持久化到宿主机项目内目录
      # 使用相对路径, 部署到任意机器时无需修改 compose 文件
      - ../data/1:/vault/data
    environment:
      VAULT_ADDR: https://kms-vault-1:8200 # 本节点对外提供服务的地址（本机 CLI 调用可用）
      NODE_IDX: "1" # 告诉 Dockerfile 的 CMD 加载 vault-1.hcl 配置
    ports:
      - "8200:8200" # 宿主机端口:容器端口, 这样容器外部就可以直接使用如 127.0.0.1:8200 访问; 在这个例子中只对外开放了节点1, vault 开启了HA集群所以如果节点 1 不是 leader 它会转发给其他节点

  # ==================================================================
  # 节点 2：集群第二个节点
  # ==================================================================
  vault-2:
    extends:
      service: vault-base
    container_name: kms-vault-2
    hostname: kms-vault-2
    volumes:
      # bind mount: 节点 2 的 Raft 数据持久化到宿主机项目内目录
      - ../data/2:/vault/data
    environment:
      VAULT_ADDR: https://kms-vault-2:8200
      NODE_IDX: "2"

  # ==================================================================
  # 节点 3：集群第三个节点
  # ==================================================================
  vault-3:
    extends:
      service: vault-base
    container_name: kms-vault-3
    hostname: kms-vault-3
    volumes:
      # bind mount: 节点 3 的 Raft 数据持久化到宿主机项目内目录
      - ../data/3:/vault/data
    environment:
      VAULT_ADDR: https://kms-vault-3:8200
      NODE_IDX: "3"

# ------------------------------------------------------------------
# 引入共享的网络/数据卷定义文件
# ------------------------------------------------------------------
include:
  - path: ./shared/cluster-env.yml
